/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vision;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelConnection.ConexaoBD;

/**
 *
 * @author carlosantonio
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBD conecta = new ConexaoBD(); 
    FormMedico form_medico = new FormMedico();
    FormUsuario form_usuario = new FormUsuario();
    FormPaciente form_paciente = new FormPaciente();
    FormAgenda form_agenda = new FormAgenda();
    
    
    public TelaPrincipal(String usuario) {
        initComponents();
        conecta.connection();
        jLabelUsuario.setText(usuario);
    } 

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonAgenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadPaciente = new javax.swing.JButton();
        jButtonCadEnfermeiras = new javax.swing.JButton();
        jButtonCadMedicos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFecharBemVindo = new javax.swing.JButton();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jMenuItemPaciente = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemAgendamento = new javax.swing.JMenuItem();
        jMenuRelatório = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBoasVindas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAgendamentoDoDia = new javax.swing.JMenuItem();
        jMenuItemAgendaMedico = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(100, 460, 180, 20);

        jLabel4.setText("Usuário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 460, 60, 16);

        jInternalFrameBemVindo.setTitle("Bem-vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agenda.png"))); // NOI18N
        jButtonAgenda.setToolTipText("Agenda");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonAgenda);
        jButtonAgenda.setBounds(20, 190, 130, 120);

        jLabel3.setText("Agendamento -");
        jPanelInternal.add(jLabel3);
        jLabel3.setBounds(20, 170, 100, 16);

        jButtonCadPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/People-Patient-Male-icon.png"))); // NOI18N
        jButtonCadPaciente.setToolTipText("Pacientes");
        jButtonCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacienteActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadPaciente);
        jButtonCadPaciente.setBounds(180, 40, 150, 120);

        jButtonCadEnfermeiras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadPacientes.png"))); // NOI18N
        jButtonCadEnfermeiras.setToolTipText("Usuários");
        jButtonCadEnfermeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEnfermeirasActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadEnfermeiras);
        jButtonCadEnfermeiras.setBounds(350, 40, 150, 120);

        jButtonCadMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CadMedicos.png"))); // NOI18N
        jButtonCadMedicos.setToolTipText("Médicos");
        jButtonCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicosActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadMedicos);
        jButtonCadMedicos.setBounds(20, 40, 150, 120);

        jLabel2.setText("Cadastros - ");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(20, 10, 90, 30);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/internalframe.png"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 1010, 320);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 60, 1010, 320);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel1.setText("Sistema de gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 360, 25);

        jButtonFecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButtonFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharBemVindo);
        jButtonFecharBemVindo.setBounds(940, 0, 60, 60);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 30, 1030, 430);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 1030, 570);

        jMenuCadastro.setText("Cadastros");

        jMenuItemMedico.setText("Médicos");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemMedico);

        jMenuItemPaciente.setText("Pacientes");
        jMenuItemPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPaciente);

        jMenuItemUsuario.setText("Usuários");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuItemAgendamento.setText("Agendamento");
        jMenuItemAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAgendamento);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatório.setText("Relatórios");
        jMenuBar1.add(jMenuRelatório);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBoasVindas.setText("Tela de boas vindas");
        jMenuItemTelaBoasVindas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBoasVindasActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBoasVindas);

        jMenuBar1.add(jMenuFerramentas);

        jMenu2.setText("Agenda");

        jMenuItemAgendamentoDoDia.setText("Agendamento do dia");
        jMenuItemAgendamentoDoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentoDoDiaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgendamentoDoDia);

        jMenuItemAgendaMedico.setText("Agenda médico");
        jMenuItemAgendaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaMedicoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgendaMedico);

        jMenuBar1.add(jMenu2);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1030, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
         try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_usuario==null){
                    form_usuario = new FormUsuario();
                    form_usuario.setVisible(true);
                    form_usuario.setResizable(false);
                }else{
                    form_usuario.setVisible(true);
                    form_usuario.setResizable(false);
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemTelaBoasVindasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBoasVindasActionPerformed
        jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBoasVindasActionPerformed

    private void jButtonCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicosActionPerformed
         try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_medico==null){
                    form_medico = new FormMedico();
                    form_medico.setVisible(true);
                    form_medico.setResizable(false);
                }else{
                    form_medico.setVisible(true);
                    form_medico.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jButtonCadMedicosActionPerformed

    private void jButtonCadEnfermeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEnfermeirasActionPerformed
         try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_usuario==null){
                    form_usuario = new FormUsuario();
                    form_usuario.setVisible(true);
                    form_usuario.setResizable(false);
                }else{
                    form_usuario.setVisible(true);
                    form_usuario.setResizable(false);
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jButtonCadEnfermeirasActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
         try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_agenda==null){
                    form_agenda = new FormAgenda();
                    form_agenda.setVisible(true);
                    form_agenda.setResizable(false);
                }else{
                    form_agenda.setVisible(true);
                    form_agenda.setResizable(false);
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBemVindoActionPerformed

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
        try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_medico==null){
                    form_medico = new FormMedico();
                    form_medico.setVisible(true);
                    form_medico.setResizable(false);
                }else{
                    form_medico.setVisible(true);
                    form_medico.setResizable(false);
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacienteActionPerformed
        try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_paciente==null){
                    form_paciente = new FormPaciente();
                    form_paciente.setVisible(true);
                    form_paciente.setResizable(false);
                }else{
                    form_paciente.setVisible(true);
                    form_paciente.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jMenuItemPacienteActionPerformed

    private void jButtonCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacienteActionPerformed
        try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_paciente==null){
                    form_paciente = new FormPaciente();
                    form_paciente.setVisible(true);
                    form_paciente.setResizable(false);
                }else{
                    form_paciente.setVisible(true);
                    form_paciente.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jButtonCadPacienteActionPerformed

    private void jMenuItemAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentoActionPerformed
        try {
            conecta.execulteSQL("select * from usuarios where  nome_usuario='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                if(form_agenda==null){
                    form_agenda = new FormAgenda();
                    form_agenda.setVisible(true);
                    form_agenda.setResizable(false);
                }else{
                    form_agenda.setVisible(true);
                    form_agenda.setResizable(false);
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para esse acesso!") ;
        }
    }//GEN-LAST:event_jMenuItemAgendamentoActionPerformed

    private void jMenuItemAgendamentoDoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentoDoDiaActionPerformed
        FormAgendaMedico agenda = new FormAgendaMedico();
        agenda.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgendamentoDoDiaActionPerformed

    private void jMenuItemAgendaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaMedicoActionPerformed
        FormAgendamentoMedico tela = new FormAgendamentoMedico();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgendaMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadEnfermeiras;
    private javax.swing.JButton jButtonCadMedicos;
    private javax.swing.JButton jButtonCadPaciente;
    private javax.swing.JButton jButtonFecharBemVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemAgendaMedico;
    private javax.swing.JMenuItem jMenuItemAgendamento;
    private javax.swing.JMenuItem jMenuItemAgendamentoDoDia;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenuItem jMenuItemPaciente;
    private javax.swing.JMenuItem jMenuItemTelaBoasVindas;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuRelatório;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
